# Generated by Django 5.2.13 on 2026-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pedido_mercadopago_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo al retirar'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], max_length=20),
        ),
    ]
