# Generated by Django 5.2.13 on 2026-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pedido_comprobante_transferencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apellido',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalle_direccion',
            field=models.CharField(blank=True, help_text='Piso, departamento, entre calles, referencias, etc.', max_length=255),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dni',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
