# Generated by Django 5.2.13 on 2026-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_pedido_apellido_pedido_ciudad_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
