# Generated by Django 5.2.13 on 2026-05-05 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_alter_itempedido_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
